const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@EclixTech";
const email = "Email";
const emailHint = "admin@email.com";
const password = "Password";
const passwordHint = "*******";
const retypePassword = "*******";
const name = "Name";
const nameHint = "eclixTech";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAcount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";
//home strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
//home_screen strings
const searchAnyThing = "Search anything...",
    todayDeals = " Today`s Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brands = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhones = "Mobile Phones",
    boysGlasses = "Boys Glasses",
    tshirts = "TShirts",
    girlsDresses = "Girls Dresses",
    featuredCategories = "Featured Categories",
    featuredProduct = "Featured Product";
